"""empty message

Revision ID: aba156db8000
Revises: 79763771b133
Create Date: 2021-10-08 14:23:27.470154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba156db8000'
down_revision = '79763771b133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_shopper', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'is_shopper')
    # ### end Alembic commands ###
